# This docker-compose file will bring up a legacy system with this command:
#   docker-compose -f docker-compose_legacy.yaml -p datanode up

# Before the command above is executed, the ropewiki/webserver_legacy image
# must be built using Dockerfile_legacy.

# NOTE: This file has NOT been tested; it is only a sketch for when the
# webserver image is ready to test.

version: '3.6'

services:

  # MySQL database; see https://hub.docker.com/_/mysql
  db:
    image: mysql:3.4  # TODO: Identify version of MySQL running for RopeWiki currently
	command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    restart: always

  # The main RopeWiki server; see Dockerfile_legacy to build the image
  webserver:
    image: ropewiki/webserver_legacy
    ports:
      - "8080:80"
    environment:
	  # This environment variable or something like it should be fed into the
	  # webserver to tell MediaWiki where to look for the database.  To this
	  # container, the address will simply be `db` (like https://db/subpath).
      - MEDIAWIKI_DATABASE=db
    depends_on:
      - db
    restart: always

  # This container is not part of the system; it just provides a convenient
  # view into the database
  adminer:
    image: adminer
	restart: always
	ports:
	  - 8081:8080
