# This docker-compose file will bring up a production legacy system with this command:
#   docker-compose -p rwlegacy up

# Before the command above is executed, the ropewiki/legacy_webserver image
# must be built according to the instructions in ../README.md.

version: '3.6'

services:

  # MySQL database; see https://hub.docker.com/_/mysql
  ropewiki_legacy_db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordonlyworksuntildbisrestored
    volumes:
      - ropewiki_database_storage:/var/lib/mysql
      - ${SQL_BACKUP_FOLDER:?SQL_BACKUP_FOLDER environment variable must be set}:/root/backup
    restart: always

  # The main RopeWiki server; see instructions in ../README.md to build the image
  ropewiki_legacy_webserver:
    image: ropewiki/legacy_webserver
    ports:
      - "8080:80"
    environment: 
      - WG_DB_SERVER=ropewiki_legacy_db
      - WG_DB_USER=ropewiki
      - WG_DB_PASSWORD=thispasswordonlyworksuntildbisrestored
      - WG_HOSTNAME=localhost:8080
    depends_on:
      - ropewiki_legacy_db
    volumes:
      - ${IMAGES_FOLDER:?IMAGES_FOLDER environment variable must be set}:/usr/share/nginx/html/ropewiki/images
    #restart: always

volumes:
  ropewiki_database_storage:
    name: ropewiki_database_storage
